# Generated by Django 4.0 on 2021-12-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id_adresse', models.IntegerField(primary_key=True, serialize=False)),
                ('rue', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamnese', models.IntegerField(primary_key=True, serialize=False)),
                ('pulsation', models.IntegerField()),
                ('oxygene', models.CharField(max_length=4)),
                ('tension', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmieres',
            fields=[
                ('numero_inami', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse_mail', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('numero_telephone', models.IntegerField()),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('nn_inami', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero_telephone', models.IntegerField()),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('numero_prescription', models.IntegerField(primary_key=True, serialize=False)),
                ('justificatif', models.CharField(max_length=150)),
                ('date_prescription', models.DateField()),
                ('date_fin', models.DateField()),
                ('nn_inami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Tournees',
            fields=[
                ('id_tournees', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id_soins', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('nomenclature', models.CharField(max_length=100)),
                ('id_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_rapport', models.IntegerField(primary_key=True, serialize=False)),
                ('observation', models.CharField(max_length=200)),
                ('id_anamnese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nn_patient', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero_telephone', models.IntegerField()),
                ('nn_perso_contact', models.IntegerField()),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id_passages', models.IntegerField(primary_key=True, serialize=False)),
                ('heure_theorique', models.TimeField()),
                ('heure_reelle', models.TimeField()),
                ('id_tournees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.tournees')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroTournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tournees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.tournees')),
                ('numero_inami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.infirmieres')),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelles',
            fields=[
                ('numero_mutuelle', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.adresse')),
                ('nn_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Kine',
            fields=[
                ('nn_inami', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero_telephone', models.IntegerField()),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.adresse')),
                ('nn_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.soins')),
                ('id_tournees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.tournees')),
                ('nn_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('numero_inami_groupe', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('numero_inami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfirmiereApp.infirmieres')),
            ],
        ),
    ]
